/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTodosRouteImport } from './routes/_authenticated.todos'
import { Route as AuthenticatedTodayRouteImport } from './routes/_authenticated.today'
import { Route as AuthenticatedScheduleRouteImport } from './routes/_authenticated.schedule'
import { Route as AuthenticatedRoutineRouteImport } from './routes/_authenticated.routine'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated.projects'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedProRouteImport } from './routes/_authenticated.pro'
import { Route as AuthenticatedPlannerRouteImport } from './routes/_authenticated.planner'
import { Route as AuthenticatedMoreRouteImport } from './routes/_authenticated.more'
import { Route as AuthenticatedGamesRouteImport } from './routes/_authenticated.games'
import { Route as AuthenticatedFeedbackRouteImport } from './routes/_authenticated.feedback'
import { Route as AuthenticatedFaqsRouteImport } from './routes/_authenticated.faqs'
import { Route as AuthenticatedDriveBackupRouteImport } from './routes/_authenticated.drive-backup'
import { Route as AuthenticatedCoursesRouteImport } from './routes/_authenticated.courses'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated.attendance'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated.settings.index'
import { Route as AuthenticatedSettingsHelpRouteImport } from './routes/_authenticated.settings.help'
import { Route as AuthenticatedSettingsDataRouteImport } from './routes/_authenticated.settings.data'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated.settings.appearance'
import { Route as AuthenticatedSettingsAdvancedRouteImport } from './routes/_authenticated.settings.advanced'
import { Route as AuthenticatedCourseCourseIdRouteImport } from './routes/_authenticated.course.$courseId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTodosRoute = AuthenticatedTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTodayRoute = AuthenticatedTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScheduleRoute = AuthenticatedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRoutineRoute = AuthenticatedRoutineRouteImport.update({
  id: '/routine',
  path: '/routine',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProRoute = AuthenticatedProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlannerRoute = AuthenticatedPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMoreRoute = AuthenticatedMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGamesRoute = AuthenticatedGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFeedbackRoute = AuthenticatedFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFaqsRoute = AuthenticatedFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDriveBackupRoute =
  AuthenticatedDriveBackupRouteImport.update({
    id: '/drive-backup',
    path: '/drive-backup',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCoursesRoute = AuthenticatedCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsHelpRoute =
  AuthenticatedSettingsHelpRouteImport.update({
    id: '/settings/help',
    path: '/settings/help',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsDataRoute =
  AuthenticatedSettingsDataRouteImport.update({
    id: '/settings/data',
    path: '/settings/data',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/settings/appearance',
    path: '/settings/appearance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsAdvancedRoute =
  AuthenticatedSettingsAdvancedRouteImport.update({
    id: '/settings/advanced',
    path: '/settings/advanced',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCourseCourseIdRoute =
  AuthenticatedCourseCourseIdRouteImport.update({
    id: '/course/$courseId',
    path: '/course/$courseId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/courses': typeof AuthenticatedCoursesRoute
  '/drive-backup': typeof AuthenticatedDriveBackupRoute
  '/faqs': typeof AuthenticatedFaqsRoute
  '/feedback': typeof AuthenticatedFeedbackRoute
  '/games': typeof AuthenticatedGamesRoute
  '/more': typeof AuthenticatedMoreRoute
  '/planner': typeof AuthenticatedPlannerRoute
  '/pro': typeof AuthenticatedProRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/routine': typeof AuthenticatedRoutineRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/today': typeof AuthenticatedTodayRoute
  '/todos': typeof AuthenticatedTodosRoute
  '/course/$courseId': typeof AuthenticatedCourseCourseIdRoute
  '/settings/advanced': typeof AuthenticatedSettingsAdvancedRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/data': typeof AuthenticatedSettingsDataRoute
  '/settings/help': typeof AuthenticatedSettingsHelpRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/courses': typeof AuthenticatedCoursesRoute
  '/drive-backup': typeof AuthenticatedDriveBackupRoute
  '/faqs': typeof AuthenticatedFaqsRoute
  '/feedback': typeof AuthenticatedFeedbackRoute
  '/games': typeof AuthenticatedGamesRoute
  '/more': typeof AuthenticatedMoreRoute
  '/planner': typeof AuthenticatedPlannerRoute
  '/pro': typeof AuthenticatedProRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/routine': typeof AuthenticatedRoutineRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/today': typeof AuthenticatedTodayRoute
  '/todos': typeof AuthenticatedTodosRoute
  '/course/$courseId': typeof AuthenticatedCourseCourseIdRoute
  '/settings/advanced': typeof AuthenticatedSettingsAdvancedRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/data': typeof AuthenticatedSettingsDataRoute
  '/settings/help': typeof AuthenticatedSettingsHelpRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/courses': typeof AuthenticatedCoursesRoute
  '/_authenticated/drive-backup': typeof AuthenticatedDriveBackupRoute
  '/_authenticated/faqs': typeof AuthenticatedFaqsRoute
  '/_authenticated/feedback': typeof AuthenticatedFeedbackRoute
  '/_authenticated/games': typeof AuthenticatedGamesRoute
  '/_authenticated/more': typeof AuthenticatedMoreRoute
  '/_authenticated/planner': typeof AuthenticatedPlannerRoute
  '/_authenticated/pro': typeof AuthenticatedProRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/routine': typeof AuthenticatedRoutineRoute
  '/_authenticated/schedule': typeof AuthenticatedScheduleRoute
  '/_authenticated/today': typeof AuthenticatedTodayRoute
  '/_authenticated/todos': typeof AuthenticatedTodosRoute
  '/_authenticated/course/$courseId': typeof AuthenticatedCourseCourseIdRoute
  '/_authenticated/settings/advanced': typeof AuthenticatedSettingsAdvancedRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/data': typeof AuthenticatedSettingsDataRoute
  '/_authenticated/settings/help': typeof AuthenticatedSettingsHelpRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/attendance'
    | '/courses'
    | '/drive-backup'
    | '/faqs'
    | '/feedback'
    | '/games'
    | '/more'
    | '/planner'
    | '/pro'
    | '/profile'
    | '/projects'
    | '/routine'
    | '/schedule'
    | '/today'
    | '/todos'
    | '/course/$courseId'
    | '/settings/advanced'
    | '/settings/appearance'
    | '/settings/data'
    | '/settings/help'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/attendance'
    | '/courses'
    | '/drive-backup'
    | '/faqs'
    | '/feedback'
    | '/games'
    | '/more'
    | '/planner'
    | '/pro'
    | '/profile'
    | '/projects'
    | '/routine'
    | '/schedule'
    | '/today'
    | '/todos'
    | '/course/$courseId'
    | '/settings/advanced'
    | '/settings/appearance'
    | '/settings/data'
    | '/settings/help'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/attendance'
    | '/_authenticated/courses'
    | '/_authenticated/drive-backup'
    | '/_authenticated/faqs'
    | '/_authenticated/feedback'
    | '/_authenticated/games'
    | '/_authenticated/more'
    | '/_authenticated/planner'
    | '/_authenticated/pro'
    | '/_authenticated/profile'
    | '/_authenticated/projects'
    | '/_authenticated/routine'
    | '/_authenticated/schedule'
    | '/_authenticated/today'
    | '/_authenticated/todos'
    | '/_authenticated/course/$courseId'
    | '/_authenticated/settings/advanced'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/data'
    | '/_authenticated/settings/help'
    | '/_authenticated/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/todos': {
      id: '/_authenticated/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof AuthenticatedTodosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/today': {
      id: '/_authenticated/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AuthenticatedTodayRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/schedule': {
      id: '/_authenticated/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthenticatedScheduleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/routine': {
      id: '/_authenticated/routine'
      path: '/routine'
      fullPath: '/routine'
      preLoaderRoute: typeof AuthenticatedRoutineRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pro': {
      id: '/_authenticated/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof AuthenticatedProRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/planner': {
      id: '/_authenticated/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof AuthenticatedPlannerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/more': {
      id: '/_authenticated/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof AuthenticatedMoreRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/games': {
      id: '/_authenticated/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof AuthenticatedGamesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feedback': {
      id: '/_authenticated/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AuthenticatedFeedbackRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/faqs': {
      id: '/_authenticated/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof AuthenticatedFaqsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/drive-backup': {
      id: '/_authenticated/drive-backup'
      path: '/drive-backup'
      fullPath: '/drive-backup'
      preLoaderRoute: typeof AuthenticatedDriveBackupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/courses': {
      id: '/_authenticated/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AuthenticatedCoursesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/help': {
      id: '/_authenticated/settings/help'
      path: '/settings/help'
      fullPath: '/settings/help'
      preLoaderRoute: typeof AuthenticatedSettingsHelpRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/data': {
      id: '/_authenticated/settings/data'
      path: '/settings/data'
      fullPath: '/settings/data'
      preLoaderRoute: typeof AuthenticatedSettingsDataRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/settings/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/advanced': {
      id: '/_authenticated/settings/advanced'
      path: '/settings/advanced'
      fullPath: '/settings/advanced'
      preLoaderRoute: typeof AuthenticatedSettingsAdvancedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/course/$courseId': {
      id: '/_authenticated/course/$courseId'
      path: '/course/$courseId'
      fullPath: '/course/$courseId'
      preLoaderRoute: typeof AuthenticatedCourseCourseIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedCoursesRoute: typeof AuthenticatedCoursesRoute
  AuthenticatedDriveBackupRoute: typeof AuthenticatedDriveBackupRoute
  AuthenticatedFaqsRoute: typeof AuthenticatedFaqsRoute
  AuthenticatedFeedbackRoute: typeof AuthenticatedFeedbackRoute
  AuthenticatedGamesRoute: typeof AuthenticatedGamesRoute
  AuthenticatedMoreRoute: typeof AuthenticatedMoreRoute
  AuthenticatedPlannerRoute: typeof AuthenticatedPlannerRoute
  AuthenticatedProRoute: typeof AuthenticatedProRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedRoutineRoute: typeof AuthenticatedRoutineRoute
  AuthenticatedScheduleRoute: typeof AuthenticatedScheduleRoute
  AuthenticatedTodayRoute: typeof AuthenticatedTodayRoute
  AuthenticatedTodosRoute: typeof AuthenticatedTodosRoute
  AuthenticatedCourseCourseIdRoute: typeof AuthenticatedCourseCourseIdRoute
  AuthenticatedSettingsAdvancedRoute: typeof AuthenticatedSettingsAdvancedRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDataRoute: typeof AuthenticatedSettingsDataRoute
  AuthenticatedSettingsHelpRoute: typeof AuthenticatedSettingsHelpRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedCoursesRoute: AuthenticatedCoursesRoute,
  AuthenticatedDriveBackupRoute: AuthenticatedDriveBackupRoute,
  AuthenticatedFaqsRoute: AuthenticatedFaqsRoute,
  AuthenticatedFeedbackRoute: AuthenticatedFeedbackRoute,
  AuthenticatedGamesRoute: AuthenticatedGamesRoute,
  AuthenticatedMoreRoute: AuthenticatedMoreRoute,
  AuthenticatedPlannerRoute: AuthenticatedPlannerRoute,
  AuthenticatedProRoute: AuthenticatedProRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedRoutineRoute: AuthenticatedRoutineRoute,
  AuthenticatedScheduleRoute: AuthenticatedScheduleRoute,
  AuthenticatedTodayRoute: AuthenticatedTodayRoute,
  AuthenticatedTodosRoute: AuthenticatedTodosRoute,
  AuthenticatedCourseCourseIdRoute: AuthenticatedCourseCourseIdRoute,
  AuthenticatedSettingsAdvancedRoute: AuthenticatedSettingsAdvancedRoute,
  AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
  AuthenticatedSettingsDataRoute: AuthenticatedSettingsDataRoute,
  AuthenticatedSettingsHelpRoute: AuthenticatedSettingsHelpRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
